
# prefix will be prepended to all ressource names
variable "prefix" {
  type    = string
  default = "doc-sample-obs-thumbnail"
}

# FunctionGraph function name
variable "function_name" {
  type    = string
  default = "createThumbnails"
}

# FunctionGraph handler name
variable "function_handler_name" {
  type    = string
  default = "com.opentelekomcloud.samples.Thumbnail.handleRequest"
}

variable "initializer_handler_name" {
  type    = string
  default = "com.opentelekomcloud.samples.Thumbnail.initializer"
}

# name of jar file to deploy, generated by 'mvn package' command
variable "jar_file_name" {
  type    = string
  default = "deployment-jar-with-dependencies.jar"
}

variable "tag_app_group" {
  type = string
  default = "doc-sample-obs-thumbnail"
}