# prefix will be prepended to all resource names
variable "prefix" {
  type    = string
  default = "doc-sample-obs-thumbnail"
}

# FunctionGraph: Function name
variable "function_name" {
  type    = string
  default = "createThumbnails"
}

# FunctionGraph: Handler name
variable "function_handler_name" {
  type    = string
  default = "com.opentelekomcloud.samples.Thumbnail.handleRequest"
}

# FunctionGraph: Initializer name
variable "initializer_handler_name" {
  type    = string
  default = "com.opentelekomcloud.samples.Thumbnail.initializer"
}

# Name of jar file to deploy, generated by 'mvn package' command
# and stored in folder  [project_folder]/target
variable "jar_file_name" {
  type    = string
  default = "deployment-jar-with-dependencies.jar"
}

# Resource tag:
variable "tag_app_group" {
  type = string
  default = "doc-sample-obs-thumbnail"
}
