
# prefix will be prepended to all ressource names
variable "prefix" {
  type    = string
  default = "sample"
}

# FunctionGraph function name
variable "function_name" {
  type    = string
  default = "Spring3-RestApp"
}

# FunctionGraph handler name
variable "function_handler_name" {
  type    = string
  default = "index.handler"
}

# name of zip file to deploy, generated by 'mvn package' command
variable "zip_file_name" {
  type    = string
  default = "opentelekomcloud-functiongraph-java-samples-doc-springboot-3x-0.0.1-SNAPSHOT.zip"
}


variable "tag_app_group" {
  type = string
  default = "doc-sample-springboot-3-x-rest"
}
