
# prefix will be prepended to all ressource names
variable "prefix" {
  type    = string
  default = "sample"
}

# FunctionGraph function name
variable "function_name" {
  type    = string
  default = "TFDeployment"
}

# FunctionGraph handler name
variable "function_handler_name" {
  type    = string
  default = "com.opentelekomcloud.samples.SampleFG.handleRequest"
}

# name of jar file to deploy, generated by 'mvn package' command
variable "jar_file_name" {
  type    = string
  default = "functiongraph-samples-doc-deploy-tf-jar-with-dependencies.jar"
}
