spring:
  application:
    name: doc-sample-springboot-3.x-rest

server:
  port: 8000

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSS'Z', UTC}) '%X{x-cff-request-id}' %p %F:%L %t - %m%n"

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: true