name: Build documentation

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - initial

jobs:
    doc-check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.12'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install tox

            - name: Run Tox for Documentation
              env:
                  GH_ACTIONS_GIT_BRANCH: ${{ github.head_ref || github.ref_name }}
              run: tox -e docs

            - name: Compress documentation into .tar.gz
              run: |
                  tar -czf docs-html.tar.gz -C doc/build/html .
                  mkdir -p ./library
                  cp docs-html.tar.gz ./library/docs-html.tar.gz
                  cp docs-html.tar.gz playbooks/docs-html.tar.gz

            - name: Write clouds.yaml
              run: |
                  mkdir -p ~/.config/openstack
                  cat > ~/.config/openstack/clouds.yaml <<EOF
                  clouds:
                    otc:
                      profile: otc
                      auth:
                        auth_url: https://iam.eu-de.otc.t-systems.com:443/v3
                        username: ${{ secrets.OTC_AUTH_USERNAME_PREVIEW }}
                        password: ${{ secrets.OTC_AUTH_PASSWORD }}
                        project_name: ${{ secrets.OTC_PROJECT_NAME_PREVIEW }}
                        user_domain_name: ${{ secrets.OTC_DOMAIN }}
                      interface: public
                      identity_api_version: 3
                      object_store_endpoint_override: ${{ secrets.OTC_ENDPOINT_STORAGE_PREVIEW }}
                  EOF

            - name: Install dependencies for Swift upload
              run: |
                  python -m pip install openstacksdk ansible requests requestsexceptions ansible
            
            - name: Upload to Swift as preview
              run: |
                ansible-playbook -i localhost, -M .github/workflows/library playbooks/upload_swift.yml
            
            # - name: Upload artifacts to OBS
            #   env:
            #       AWS_ACCESS_KEY_ID: ${{ secrets.OTC_ACCESS_KEY_ID }}
            #       AWS_SECRET_ACCESS_KEY: ${{ secrets.OTC_SECRET_ACCESS_KEY }}
            #       AWS_DEFAULT_REGION: eu-de
            #   run: |
            #       pip install "awscli<1.33.0"
            #       export TARGET_PATH=s3://helpcenter-docs/opentelekomcloud-functiongraph-java/${{ github.head_ref || github.ref_name }}/
            #       export ENDPOINT_URL=https://obs.eu-de.otc.t-systems.com
            #       aws s3 rm "$TARGET_PATH" --recursive --endpoint-url "$ENDPOINT_URL"
            #       aws s3 cp doc/build/html "$TARGET_PATH" \
            #         --endpoint-url "$ENDPOINT_URL" \
            #         --recursive
                    

            
