name: Lint GitHub Workflows

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  actionlint:
    name: Run actionlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          fail_level: any
